controller_list:
  - name: fake_left_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm_joint_1
      - left_arm_joint_2
      - left_arm_joint_3
      - left_arm_joint_4
      - left_arm_joint_5
      - left_arm_joint_6
      - left_arm_joint_7
  - name: fake_right_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - right_arm_joint_1
      - right_arm_joint_2
      - right_arm_joint_3
      - right_arm_joint_4
      - right_arm_joint_5
      - right_arm_joint_6
      - right_arm_joint_7
  - name: fake_body_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_driven_gear
      - joint_lifting_rod
  - name: fake_rightEE_group_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint_right
  - name: fake_leftEE_group_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint_left
  - name: fake_all_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_driven_gear
      - joint_lifting_rod
      - left_arm_joint_1
      - left_arm_joint_2
      - left_arm_joint_3
      - left_arm_joint_4
      - left_arm_joint_5
      - left_arm_joint_6
      - left_arm_joint_7
      - finger_joint_left
      - right_arm_joint_1
      - right_arm_joint_2
      - right_arm_joint_3
      - right_arm_joint_4
      - right_arm_joint_5
      - right_arm_joint_6
      - right_arm_joint_7
      - finger_joint_right
initial:  # Define initial robot poses per group
  - group: left_arm_group
    pose: left_arm_home
  - group: right_arm_group
    pose: right_arm_group
  - group: body_group
    pose: body_home
  - group: rightEE_group
    pose: rightEE_home
  - group: leftEE_group
    pose: leftEE_home