right_arm_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_arm_joint_1
    - right_arm_joint_2
    - right_arm_joint_3
    - right_arm_joint_4
    - right_arm_joint_5
    - right_arm_joint_6
    - right_arm_joint_7
  gains:
    right_arm_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_arm_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_arm_joint_1
    - left_arm_joint_2
    - left_arm_joint_3
    - left_arm_joint_4
    - left_arm_joint_5
    - left_arm_joint_6
    - left_arm_joint_7
  gains:
    left_arm_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
base_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_driven_gear
    - joint_lifting_rod
  gains:
    joint_driven_gear:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_lifting_rod:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
body_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_driven_gear
    - joint_lifting_rod
  gains:
    joint_driven_gear:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_lifting_rod:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
rightEE_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robotiq_85_left_knuckle_joint_right
  gains:
    robotiq_85_left_knuckle_joint_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
leftEE_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robotiq_85_left_knuckle_joint_right
  gains:
    robotiq_85_left_knuckle_joint_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1